#!/bin/bash

# See more at
# https://github.com/end-4/dots-hyprland-wiki/issues/3

set -e
script=$(readlink -f "$0")
base=$(dirname "$script")/src/content/docs
json_file=$(dirname "$script")/l10n-notify.json

src_locale=en
src_locale_name=English

echo "================================"
echo "================================ STEP 1: Path detection and transforming"
echo "================================"
abs_paths=()
for path in "$@";do
  abs_path=$(readlink -f "$path") || { echo "[$0]: Failed to get the absolute path of file \"$path\". Aborting..." ; exit 1 ; }
  test -f $abs_path || { echo "[$0]: The file \"$abs_path\" does not exists or is a directory. Aborting..." ; exit 1 ; }
  echo $abs_path|grep -q "$base/$src_locale/dev/" && { echo "[$0]: The file \"$abs_path\" seems to be a Dev Note. Skipping..." ; continue ; }
  echo $abs_path|grep -q "$base/$src_locale/" || { echo "[$0]: The file \"$abs_path\" seems not to be a doc in $src_locale_name. Aborting..." ; exit 1 ; }
  abs_paths+=("$abs_path")
done

echo "--------------------------------"
echo "-------------------------------- Result of STEP 1"
echo "--------------------------------"
echo "[$0]: Every file path has been transformed into absolute path. Here they are:"
for path in "${abs_paths[@]}";do
  echo "    $path"
done


echo "================================"
echo "================================ STEP 2: Parsing json"
echo "================================"
while read -r string; do
  locale+=("$string")
done < <(jq -r 'keys[]' $json_file)

notif=()
for key in "${locale[@]}"; do
  echo $key
  value=$(jq -r ".\"$key\"" $json_file)
  notif+=("$value""$(date +%F)")
done

echo "[$0]: Notifications for different locales have been loaded."
for ((i=0; i<${#locale[@]}; i++)); do
  echo "-- Entry $i: "
  echo "--   ├─locale = \"${locale[i]}\""
  echo "--   ├─notif  = \"${notif[i]}\""
  echo "--   └─root   = \"$base/${locale[i]}\""
done

echo "================================"
echo "================================ STEP 3: Processing translation file"
echo "================================"
h="       │   └─"
h2="       │   ├─"
for ((i=0; i<${#locale[@]}; i++)); do
echo "--------------------------"
echo "-- Processing: "
echo "--   ├─locale = \"${locale[i]}\""
echo "--   ├─notif  = \"${notif[i]}\""
echo "--   └─root   = \"$base/${locale[i]}\""
  if [ "${locale[i]}" = "$src_locale" ]; then echo "   Translation directory \"$base/${locale[i]}\" is of English, skipping..."; continue ; fi
  test -d "$base/${locale[i]}" || { echo "   Translation directory \"$base/${locale[i]}\" does not exists, skipping..."; continue ; }
  for path in "${abs_paths[@]}";do
    loc_path="$base/${locale[i]}/"$(realpath --relative-to="$base/$src_locale/" "$path")
    # TODO: better handling when target file does not exists
    test -f $loc_path || { echo "   The translation file \"$loc_path\" does not exists or is a directory. Aborting..." ; exit 1 ; }
    echo "++     ├─file = \"$loc_path\""
    line_beg=$(awk '/^:::caution\[L10N-NOTIFY\]$/{print NR;exit}' $loc_path)
    line_end=$(awk '/^:::$/{print NR;exit}' $loc_path)
    if [ -z "$line_beg" ]; then
      echo "${h2}Mark string not found."
      fr_end=$(awk '/^---$/{count++; if(count==2) {print NR; exit}}' "$loc_path")
      if [ -z "$fr_end" ]; then
        echo "${h}Frontmatter not found or not ended. Aborting...";exit 1
      else
        echo "${h}Frontmatter end at $fr_end ."
        sed -i "$((fr_end+1))i:::" "$loc_path"
        sed -i "$((fr_end+1))i${notif[i]}" "$loc_path"
        sed -i "$((fr_end+1))i:::caution[L10N-NOTIFY]" "$loc_path"
      fi
    elif [ -z "$line_end" ]; then
      echo "${h}Mark string found at line $line_beg, but the aside has no end, something must be wrong. Aborting..."; exit 1
    elif [ $line_end -eq $(($line_beg+1)) ]; then
      echo "${h}Mark string found at line $line_beg, and the aside end at line $line_end, i.e. it contains nothing."
      sed -i "${line_end}i${notif[i]}" "$loc_path"
    elif [ $line_end -eq $(($line_beg+2)) ]; then
      echo "${h}Mark string found at line $line_beg, and the aside end at line $line_end, i.e. it contains one line."
      sed -i "${line_end}i${notif[i]}" "$loc_path"
      sed -i "$((line_beg+1))d" "$loc_path"
    else
      echo "${h}Mark string found at line $line_beg, but the aside end at line $line_end, something must be wrong. Aborting..."; exit 1
    fi
  done
done
